export const SET_USER_NAME = "SET_USER_NAME";
export const SET_BASIC_INFO = "SET_BASIC_INFO";

// additional info

export const SET_IDENTITY = "SET_IDENTITY";
export const SET_DRIVINGLICENSE = "SET_DRIVINGLICENSE";
export const SET_VEHICLEDOCUMENT = "SET_VEHICLEDOCUMENT";
export const SET_VEHICLEREQUIRMENTS = "SET_VEHICLEREQUIRMENTS";
export const UPDATE_IDENTITY = "SET_IDENTITY";
export const UPDATE_DRIVINGLICENSE = "SET_DRIVINGLICENSE";
export const UPDATE_VEHICLEDOCUMENT = "SET_VEHICLEDOCUMENT";
export const UPDATE_VEHICLEREQUIRMENTS = "SET_VEHICLEREQUIRMENTS";
export const UPDATE_ADDITIONAL_INFO = "UPDATE_ADDITIONAL_INFO";
export const SET_ADDITIONAL_INFO = "SET_ADDITIONAL_INFO";
export const REMOVE_ADDITIONAL_INFO = "REMOVE_ADDITIONAL_INFO";
export const CHANGE_STATUS = "CHANGE_STATUS";
